name: tokenspiceenv
dependencies:
  - python==3.8
  - pip
  - numpy
  - pandas
  - matplotlib
  - pip:
    - cadcad
    - hvplot
    - plotly
    - enforce-typing
    - pytest
    - web3
    - deprecated
    - pycryptodomex
    - tqdm
    - pytz
    - eth-account
    - eth-keys
    - eth-utils
    - names